services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../:/app
      - node_modules:/app/node_modules
    command: sh -c "npm i --legacy-peer-deps && npx expo install --fix && npx expo start --tunnel"
    environment:
      # Pour mobile: utilisez votre IP locale (ipconfig | findstr IPv4)
      # Pour tester, changez l'IP ci-dessous: http://VOTRE_IP:8000/api
      # Exemple détecté: 10.6.3.13 (vérifiez que c'est votre IP sur le réseau WiFi)
      - EXPO_PUBLIC_API_URL=${EXPO_PUBLIC_API_URL:-http://10.6.3.13:8000/api}
      - NPM_CONFIG_UNSAFE_PERM=true
      - NPM_CONFIG_LEGACY_PEER_DEPS=true
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"      # Metro bundler
      - "19006:19006"    # Expo web

volumes:
  node_modules:
