services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../:/app
      - node_modules:/app/node_modules
    command: sh -c "npm i --legacy-peer-deps && npx expo install --fix && npx expo start --tunnel"
    environment:
      - EXPO_PUBLIC_API_URL=${EXPO_PUBLIC_API_URL:-http://host.docker.internal:8000/api}
      - NPM_CONFIG_UNSAFE_PERM=true
      - NPM_CONFIG_LEGACY_PEER_DEPS=true
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"      # Metro bundler
      - "19006:19006"    # Expo web

volumes:
  node_modules:
